version: '3.7'
services:
    web:
        build:
            context: .
            target: web
        environment:
            APP_ENV: dev
            XDEBUG_ENABLED: 1
            DATABASE_URL: mysql://user:password@db:3306/tribe?serverVersion=mariadb-10.6.17
        volumes:
            - ./:/var/www/html:rw,cached
            - ./docker/php/php.dev.ini:/usr/local/etc/php/conf.d/php.dev.ini:rw,cached
        networks:
            - default
            - web
        labels:
            traefik.enable: 'true'
            traefik.http.routers.tribe.rule: 'Host(`tribe.localhost`)'
            traefik.http.routers.tribe.entrypoints: web
            traefik.docker.network: web

    db:
        image: mariadb:10.6
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
            - 33543:3306
        volumes:
        - 'db-volume:/var/lib/mysql'

volumes:
  db-volume:

networks:
  web:
      external: true