food_recipes:
    resource:
        path: ../src/FoodRecipes/Ports/Controller
        namespace: Przper\Tribe\FoodRecipes\Ports\Controller
    type: attribute

food_recipes_api:
    resource:
        path: ../src/FoodRecipes/Ports/Api
        namespace: Przper\Tribe\FoodRecipes\Ports\Api
    type: attribute
    prefix: /api/v1
    name_prefix: food_recipes.api.
    format: json
    locale: en

provisioning:
    resource:
        path: ../src/Provisioning/Ports/Controller
        namespace: Przper\Tribe\Provisioning\Ports\Controller
    type: attribute

worked_time:
    resource:
        path: ../src/WorkedTime/Ports/Controller
        namespace: Przper\Tribe\WorkedTime\Ports\Controller
    type: attribute
