food_recipes:
    resource:
        path: ../src/FoodRecipes/Ports/Web
        namespace: Przper\Tribe\FoodRecipes\Ports\Web
    type: attribute

food_recipes_api:
    resource:
        path: ../src/FoodRecipes/Ports/Api
        namespace: Przper\Tribe\FoodRecipes\Ports\Api
    type: attribute
    prefix: /api/v1
    name_prefix: food_recipes.api.
    format: json
    locale: en

provisioning:
    resource:
        path: ../src/Provisioning/Ports/Web
        namespace: Przper\Tribe\Provisioning\Ports\Web
    type: attribute

provisioning_api:
    resource:
        path: ../src/Provisioning/Ports/Api
        namespace: Przper\Tribe\Provisioning\Ports\Api
    type: attribute
    prefix: /api/v1
    name_prefix: provisioning.api.
    format: json
    locale: en

worked_time:
    resource:
        path: ../src/WorkedTime/Ports/Controller
        namespace: Przper\Tribe\WorkedTime\Ports\Controller
    type: attribute

identity:
    resource:
        path: ../src/Identity/Ports/Web
        namespace: Przper\Tribe\Identity\Ports\Web
    type: attribute
    name_prefix: identity.