# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Przper\Tribe\:
        bind:
            $polcodeLinkApiKey: "%env(POLCODE_LINK_APIKEY)%"
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    _instanceof:
        Przper\Tribe\Shared\Domain\DomainEventListenerInterface:
            tags:
                - domain_event_listener

    Doctrine\DBAL\Connection:
        factory: ['Przper\Tribe\Shared\Infrastructure\DBAL\DoctrineConnectionFactory', 'createConnection']
        arguments:
            - '%env(resolve:DATABASE_URL)%'

    Przper\Tribe\Shared\Domain\DomainEventDispatcher:
        arguments:
            $listeners: !tagged_iterator domain_event_listener

when@test:
    services:
        Przper\Tribe\Shared\Domain\DomainEventDispatcherInterface:
            class: Tests\Doubles\InMemoryInfrastructure\Shared\InMemoryDomainEventDispatcher

        Przper\Tribe\FoodRecipes\Domain\RecipeRepositoryInterface:
            class: Tests\Doubles\InMemoryInfrastructure\FoodRecipes\InMemoryRecipeRepository

        Przper\Tribe\FoodRecipes\Application\Projection\RecipeDetailProjectionInterface:
            class: Tests\Doubles\InMemoryInfrastructure\FoodRecipes\InMemoryRecipeDetailProjection

        Przper\Tribe\FoodRecipes\Application\Projection\RecipeIndexProjectionInterface:
            class: Tests\Doubles\InMemoryInfrastructure\FoodRecipes\InMemoryRecipeIndexProjection
